CREATE DATABASE AdvAbc
USE AdvAbc

CREATE TABLE Usuarios
(
	Id INT PRIMARY KEY IDENTITY(11,1),
	Telefone VARCHAR (30) NOT NULL,
	Email VARCHAR(30) NOT NULL,
	Nome VARCHAR(30)NOT NULL,
	Endereco VARCHAR(30) NOT NULL,
	Nascimento DATETIME NOT NULL,
	Contato DATETIME NOT NULL,
	Observacoes VARCHAR(MAX) NOT NULL,
	Cargo VARCHAR(30) NOT NULL,
	Empresa VARCHAR (30) NOT NULL,
	
)

